name: Report Size Deltas

# See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/report-size-deltas.yml"
  schedule:
    # Run at the minimum interval allowed by GitHub Actions.
    - cron: "*/5 * * * *"
  workflow_dispatch:
  repository_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Comment size deltas reports to PRs
        uses: arduino/report-size-deltas@main
        with:
          # The name of the workflow artifact created by the "Compile Examples" workflow
          sketches-reports-source: sketches-reports
