name: Report Size Deltas

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      # See: https://github.com/arduino/report-size-deltas/README.md
      - name: Comment size deltas reports to PRs
        uses: arduino/report-size-deltas@main
