name: Report Size Deltas

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      # See: https://github.com/arduino/report-size-deltas/README.md
      uses: arduino/report-size-deltas@v1
      with:
        # Regex matching the names of the workflow artifacts created by the "Compile Examples" workflow
        sketches-reports-source: ^sketches-report-.+
